version: '2'
services:
  jekyll:
    container_name: oceanhub_jekyll
    build: ./jekyll/.
    ports:
      - "23400:4000"
    volumes:
      - ./docs:/workdir
    command: /bin/bash fake-daemon.sh
  nginx:
    container_name: oceanhub_nginx
    build: ./nginx/.
    ports:
      - "21030:80"
    volumes:
      - ./workdir:/workdir
    command: /bin/bash fake-daemon.sh
    links:
      - jekyll
