# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DumpTask',
            fields=[
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID задачи')),
                ('status', models.CharField(choices=[('-1', 'Ошибка'), ('0', 'Новая задача'), ('1', 'Идёт обработка'), ('2', 'Готово')], default='0', max_length=2, verbose_name='Статус выполнения задачи')),
                ('file_link', models.CharField(blank=True, default='', max_length=200, verbose_name='Путь к файлу для обработки')),
            ],
        ),
    ]
