# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dump', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dumptask',
            name='file_link',
        ),
        migrations.AddField(
            model_name='dumptask',
            name='file_path',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Путь к файлy с дампом'),
        ),
    ]
