# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dump', '0002_auto_20170529_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='dumptask',
            name='file_size',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Размер файла'),
        ),
    ]
