# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 15:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dump', '0003_dumptask_file_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dumptask',
            old_name='file_path',
            new_name='file_name',
        ),
    ]
