# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-02 09:59
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
import django.contrib.gis.geos.polygon
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(default='')),
                ('poly', django.contrib.gis.db.models.fields.PolygonField(default=django.contrib.gis.geos.polygon.Polygon(((-15.743695, 77.781198), (27.955703, 77.781198), (27.955703, 59.453594), (-15.743695, 59.453594), (-15.743695, 77.781198))), srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(6, 70), srid=4326, unique=True)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, unique_for_date=True)),
                ('sst', models.FloatField(null=True, verbose_name='Температура поверхности океана, К')),
                ('ci', models.FloatField(null=True, verbose_name='Ледяное покрытие океана')),
                ('tcc', models.FloatField(null=True, verbose_name='Облачность')),
                ('t2m', models.FloatField(null=True, verbose_name='Температура у поверхности, К')),
                ('sw', models.FloatField(null=True, verbose_name='Скорость ветра у поверхности океана, м')),
                ('elevation', models.FloatField(null=True, verbose_name='Высота поверхности океана, м')),
            ],
        ),
    ]
