# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-02 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocean', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='chlor_a',
            field=models.FloatField(null=True, verbose_name='Концентрация хлорофила'),
        ),
    ]
