# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-16 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ocean', '0002_spot_chlor_a'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestMesh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('lon', models.FloatField(default=0)),
                ('lat', models.FloatField(default=0)),
                ('sst', models.FloatField(default=0)),
            ],
        ),
    ]
