# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-21 09:49
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ocean', '0003_testmesh'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bathymetric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(6, 70), srid=4326, unique=True)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, unique_for_date=True)),
                ('elevation', models.FloatField(null=True, verbose_name='Высота поверхности океана, м')),
            ],
        ),
        migrations.CreateModel(
            name='Chlorophyll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(6, 70), srid=4326, unique=True)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, unique_for_date=True)),
                ('chlor_a', models.FloatField(null=True, verbose_name='Концентрация хлорофила')),
            ],
        ),
        migrations.CreateModel(
            name='SST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(6, 70), srid=4326, unique=True)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, unique_for_date=True)),
                ('sst', models.FloatField(null=True, verbose_name='Температура поверхности океана, К')),
            ],
        ),
    ]
