# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-21 09:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocean', '0004_bathymetric_chlorophyll_sst'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='poly',
        ),
    ]
