# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-02 14:45
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ocean', '0006_region_mpoly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chlorophyll',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='chlorophyll',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(6, 70), srid=4326),
        ),
        migrations.AlterField(
            model_name='sst',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sst',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(6, 70), srid=4326),
        ),
    ]
