# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-06 08:41
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.collections
import django.contrib.gis.geos.polygon
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocean', '0008_auto_20170302_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='mpoly',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(default=django.contrib.gis.geos.collections.MultiPolygon(django.contrib.gis.geos.polygon.Polygon(((5.897592, 59.453594), (-15.743695, 64.412255), (15.617894, 77.781198), (27.955703, 70.515584), (5.897592, 59.453594))), django.contrib.gis.geos.polygon.Polygon(((145.933452, 43, 902974), (151.670932, 43, 902974), (151.670932, 39, 980028), (145.933452, 39, 980028), (145.933452, 43, 902974)))), srid=4326),
        ),
        migrations.AlterField(
            model_name='region',
            name='slug',
            field=models.SlugField(default='default'),
        ),
        migrations.AlterField(
            model_name='region',
            name='title',
            field=models.CharField(default='Default regions of interest', max_length=50),
        ),
    ]
