# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-30 13:21
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ocean', '0010_auto_20170321_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeaIceCover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(6, 70), srid=4326)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('ci', models.FloatField(null=True, verbose_name='Ледяное покрытие океана, да - нет')),
            ],
        ),
    ]
