# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-12 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ocean', '0012_auto_20170411_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bathymetric',
            name='datetime',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='chlorophyll',
            name='datetime',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='seaicecover',
            name='datetime',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
