# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-18 11:30
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ocean', '0013_auto_20170412_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='T2M',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(6, 70), srid=4326)),
                ('datetime', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('t2m', models.FloatField(null=True, verbose_name='Температура у поверхности, К')),
            ],
        ),
        migrations.CreateModel(
            name='TCC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(6, 70), srid=4326)),
                ('datetime', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('tcc', models.FloatField(null=True, verbose_name='Облачность')),
            ],
        ),
    ]
