# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 16:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocean', '0015_auto_20170420_1044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bathymetric',
            old_name='elevation',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='sst',
            old_name='sst',
            new_name='value',
        ),
    ]
