# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 10:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocean', '0016_auto_20170420_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seaicecover',
            old_name='ci',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='t2m',
            old_name='t2m',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='tcc',
            old_name='tcc',
            new_name='value',
        ),
    ]
