# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 09:11
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ocean', '0017_auto_20170426_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeaWindSpeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(6, 70), srid=4326)),
                ('datetime', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('value', models.FloatField(null=True, verbose_name='Скорость ветра у поверхности океана, м')),
            ],
        ),
    ]
