# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocean', '0023_auto_20170519_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteristic',
            name='description',
            field=models.CharField(default='', max_length=200, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name='Название'),
        ),
    ]
