# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocean', '0024_auto_20170519_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristic',
            name='description',
            field=models.CharField(blank=True, max_length=200, verbose_name='Описание'),
        ),
    ]
