# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 14:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocean', '0025_auto_20170519_1354'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SST',
            new_name='SeaSurfaceTemperature',
        ),
        migrations.RenameModel(
            old_name='T2M',
            new_name='Temperature',
        ),
        migrations.RenameModel(
            old_name='TCC',
            new_name='TotalCloudCover',
        ),
    ]
