# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-14 10:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='', unique=True, verbose_name='Сервер')),
                ('link', models.SlugField(verbose_name='Ссылка')),
                ('max_connections', models.PositiveSmallIntegerField(default=1, verbose_name='Максимальное кол-во соединений')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания')),
                ('regexp_mask', models.CharField(max_length=500, verbose_name='Маска регулярного выражения')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='download.Server')),
            ],
        ),
    ]
