# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-14 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='link',
            field=models.SlugField(max_length=500, verbose_name='Ссылка'),
        ),
    ]
