# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-14 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0002_auto_20170314_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='link',
            field=models.CharField(max_length=500, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='server',
            name='slug',
            field=models.SlugField(default='', unique=True, verbose_name='Уникальное обозначение сервера'),
        ),
    ]
