# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-14 10:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0003_auto_20170314_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='datetime',
            new_name='date_time',
        ),
        migrations.AddField(
            model_name='task',
            name='date_end',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Период, по'),
        ),
        migrations.AddField(
            model_name='task',
            name='date_start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Период, с'),
        ),
    ]
