# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-14 10:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0006_task_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='timestamp',
        ),
    ]
