# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-14 10:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0007_remove_task_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='task',
            name='date_start',
        ),
        migrations.AddField(
            model_name='task',
            name='timestamp',
            field=models.DateField(auto_now_add=True, default=datetime.date(2017, 3, 14)),
            preserve_default=False,
        ),
    ]
