# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-14 10:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0010_remove_task_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='timestamp',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
