# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-14 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0012_auto_20170314_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
