# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-14 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0013_auto_20170314_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(default='new', editable=False, max_length=50, verbose_name='Статут выполнения'),
        ),
    ]
