# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-14 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0014_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='passes',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='Кол-во проходов'),
        ),
    ]
