# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-14 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0016_auto_20170314_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_end',
            field=models.DateField(default=None, verbose_name='Период, по'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_start',
            field=models.DateField(default=None, verbose_name='Период, с'),
        ),
    ]
