# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-14 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0017_auto_20170314_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_end',
            field=models.DateField(blank=True, default=None, verbose_name='Период, по'),
        ),
    ]
