# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-14 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0019_auto_20170314_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='note',
            field=models.CharField(default='', max_length=500, verbose_name='Примечание'),
        ),
    ]
