# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-14 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0020_task_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='expected_files_number',
            field=models.PositiveSmallIntegerField(default=1000, verbose_name='Предполагаемое кол-во файлов'),
        ),
    ]
