# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-14 12:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0021_task_expected_files_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='url',
            new_name='site_url',
        ),
    ]
