# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-14 13:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0024_auto_20170314_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='server_url',
            new_name='url',
        ),
    ]
