# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-14 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0025_auto_20170314_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='note',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Примечание'),
        ),
    ]
