# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-14 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0026_auto_20170314_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='expected_files_number',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Предполагаемое кол-во файлов'),
        ),
    ]
