# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-14 16:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0028_task_file_names_generator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='file_names_generator',
            new_name='files_names_generator',
        ),
    ]
