# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-14 16:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0029_auto_20170314_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='regexp_mask',
        ),
    ]
