# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-14 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0030_remove_task_regexp_mask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='files_names_generator',
            field=models.TextField(default='', verbose_name='Генератор имен файлов для загрузки;         предполагает использование атрибута date'),
        ),
    ]
