# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-15 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0034_auto_20170315_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='files_names_generator',
            field=models.TextField(default='', verbose_name='В формате Python: список имён файлов для загрузки;         или генератор имен файлов         (предполагает использование атрибута date)'),
        ),
    ]
