# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-16 10:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0035_auto_20170315_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='expected_files_number',
        ),
    ]
