# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-16 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0036_remove_task_expected_files_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='store_prefix',
            field=models.CharField(blank=True, default='new', max_length=50, verbose_name='Префикс хранения'),
        ),
    ]
