# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-17 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0038_auto_20170316_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorePrefix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200, verbose_name='Описание')),
                ('slug', models.SlugField(default='', unique=True, verbose_name='Уникальное обозначение')),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='store_prefix',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='download.StorePrefix'),
        ),
    ]
