# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-17 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0042_auto_20170317_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeprefix',
            name='slug',
            field=models.SlugField(blank=True, default='', unique=True, verbose_name='Уникальное обозначение'),
        ),
    ]
