# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-24 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0044_auto_20170317_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='result',
            field=models.TextField(blank=True, default='', verbose_name='Результат'),
        ),
        migrations.AddField(
            model_name='task',
            name='run',
            field=models.BooleanField(default=False, verbose_name='Выполнить'),
        ),
    ]
