# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-21 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ocean', '0009_auto_20170306_0841'),
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200, verbose_name='Название')),
                ('tag', models.SlugField(default='', verbose_name='Тэг в netCDF/hdf файле')),
                ('store_prefix', models.SlugField(blank=True, default='', verbose_name='Префикс хранения файлов')),
                ('file_mask', models.CharField(blank=True, default='', max_length=50, verbose_name='Маска поиска файла')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('date_start', models.DateField(default=None, verbose_name='Период, с')),
                ('date_end', models.DateField(blank=True, default=None, null=True, verbose_name='Период, по')),
                ('status', models.CharField(default='new', editable=False, max_length=50, verbose_name='Статут выполнения')),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parse.Characteristic')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocean.Region')),
            ],
        ),
    ]
