# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-21 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristic',
            name='store_prefix',
            field=models.SlugField(default='', verbose_name='Префикс хранения файлов'),
        ),
    ]
