# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-23 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0002_auto_20170321_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='result',
            field=models.TextField(default='', verbose_name='Результат'),
        ),
        migrations.AddField(
            model_name='task',
            name='run',
            field=models.BooleanField(default=False, verbose_name='Выполнить'),
        ),
    ]
