# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-23 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0003_auto_20170323_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='result',
            field=models.TextField(blank=True, default='', verbose_name='Результат'),
        ),
    ]
