# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0004_auto_20170323_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristic',
            name='tag',
            field=models.SlugField(default='', verbose_name='Опция для парсера (например, тэг в netCDF/hdf файле)'),
        ),
    ]
