# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0008_auto_20170519_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristic',
            name='model',
            field=models.CharField(max_length=200, verbose_name='Модель данных'),
        ),
    ]
