# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocean', '0022_characteristic'),
        ('parse', '0010_auto_20170519_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='characteristic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ocean.Characteristic'),
            preserve_default=False,
        ),
    ]
