# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 09:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0011_task_characteristic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='characteristic',
        ),
        migrations.RemoveField(
            model_name='task',
            name='region',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
