# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ocean', '0025_auto_20170519_1354'),
        ('parse', '0012_auto_20170519_0927'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('date_start', models.DateField(default=None, verbose_name='Период, с')),
                ('date_end', models.DateField(blank=True, default=None, null=True, verbose_name='Период, по')),
                ('status', models.CharField(default='new', editable=False, max_length=50, verbose_name='Статут выполнения')),
                ('result', models.TextField(blank=True, default='', verbose_name='Результат')),
                ('run', models.BooleanField(default=False, verbose_name='Выполнить')),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocean.Characteristic')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocean.Region')),
            ],
        ),
    ]
