# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0014_task_process_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='process_type',
            field=models.CharField(choices=[('byday', 'Файлы разложены по дням, дата задаётся извне'), ('set', 'Один файл, дата содержится внутри')], default='byday', max_length=50, verbose_name='Тип обработки данных'),
        ),
    ]
