# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0017_auto_20170525_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='process_type',
            field=models.CharField(choices=[('byday', 'Файлы разложены по дням'), ('set', 'Один файл')], default='byday', max_length=50, verbose_name='Тип обработки данных'),
        ),
    ]
